site_name: The Data-flo Cookbook
theme:
  name: material

markdown_extensions: 
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences  
  - footnotes  
  - pymdownx.highlight:
      anchor_linenums: true